name: Publish to NuGet

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '7.0.x'

    - name: Restore dependencies
      run: dotnet restore ./Cybertron/Cybertron.Domain/Cybertron.Domain.csproj

    - name: Build
      run: dotnet build  ./Cybertron/Cybertron.Domain/Cybertron.Domain.csproj --configuration Release --no-restore

    - name: Pack
      run: dotnet pack ./Cybertron/Cybertron.Domain/Cybertron.Domain.csproj  --configuration Release --no-build -o ./nupkg

    - name: Publish to NuGet
      run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
